### ISSUE TITLE
When multiple trees contain a given file, which should win?

### ISSUE THREAD

**Issue by rwjblue** [SparshithNR/fs-merger#15]
In _general_ with `broccoli-merge-trees` rules, the "last one wins" (but only if you've specified `{ overwrite: true }`. This library also supports "last wins", but it still reads from each tree. See implementation here:

https://github.com/SparshithNR/fs-merger/blob/021b9075fe08d28edb99c550bdae6b41080e3fa4/index.js#L78-L89

If we do indeed intend to support "last wins" we should update the implementations to avoid reading files only to throw away those results (e.g. we should iterate backwards and return the first match).

**Comment by SparshithNR** [comment]
There are two cases.
readFileSync, lstatSync, statSync cases `last wins`
readdirSync, readdir case `results get merged from first to last`. Simulating that all the files are present under the same folder.

I will make change loop from reverse and send the first match.
