### ISSUE TITLE
`readFileMeta` seems unused?

### ISSUE THREAD

**Issue by rwjblue** [SparshithNR/fs-merger#16]
https://github.com/SparshithNR/fs-merger/blob/021b9075fe08d28edb99c550bdae6b41080e3fa4/index.js#L99-L134

The broccoli PR does not use it AFAICT

**Comment by SparshithNR** [comment]
It is used in broccoli-persistent-filter PR. 
https://github.com/stefanpenner/broccoli-persistent-filter/blob/d084c3e4d7692f986c9ac136269eec183e57ed15/index.js#L252
