### ISSUE TITLE
The `dist` folder is missing in `3.2.0`

### ISSUE THREAD

**Issue by sandydoo** [SparshithNR/fs-merger#49]
😅
@thoov, pinging you before people start freaking out

**Comment by betocantu93** [comment]
Oh that was fast

**Comment by sandydoo** [comment]
Thank you, @thoov! Have a great weekend!

**Comment by thoov** [comment]
Will be released shortly as 3.2.1. Thanks for the quick issue!

**Comment by thoov** [comment]
3.2.1 has been released with dist :-)
